defmodule Cascade.Repo.Migrations.ChangeDocumentTagKey do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint("document_tags", "document_tags_pkey")

    alter table(:document_tags) do
      modify :tag_id, :uuid, primary_key: true
      modify :document_id, :uuid, primary_key: true

      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      remove :id
    end
  end

  def down do
    drop constraint("document_tags", "document_tags_pkey")

    alter table(:document_tags) do
      # This is the `down` migration of the statement:
      #
      #     remove :id
      #

      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      modify :document_id, :uuid, primary_key: false
      modify :tag_id, :uuid, primary_key: false
    end
  end
end
