defmodule Cascade.Repo.Migrations.ReviseKeys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:document_tags) do
      modify :tag_id, :uuid, null: false
      modify :document_id, :uuid, null: false
    end
  end

  def down do
    alter table(:document_tags) do
      modify :document_id, :uuid, null: true
      modify :tag_id, :uuid, null: true
    end
  end
end
